# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
